import 'package:flutter_chat_ui/flutter_chat_ui.dart';

class MyChatTheme extends ChatTheme {
  MyChatTheme({
    required super.attachmentButtonIcon,
    required super.attachmentButtonMargin,
    required super.backgroundColor,
    required super.dateDividerMargin,
    required super.dateDividerTextStyle,
    required super.deliveredIcon,
    required super.documentIcon,
    required super.emptyChatPlaceholderTextStyle,
    required super.errorColor,
    required super.errorIcon,
    required super.inputBackgroundColor,
    required super.inputSurfaceTintColor,
    required super.inputElevation,
    required super.inputBorderRadius,
    required super.inputMargin,
    required super.inputPadding,
    required super.inputTextColor,
    required super.inputTextDecoration,
    required super.inputTextStyle,
    required super.messageBorderRadius,
    required super.messageInsetsHorizontal,
    required super.messageInsetsVertical,
    required super.messageMaxWidth,
    required super.primaryColor,
    required super.receivedEmojiMessageTextStyle,
    required super.receivedMessageBodyTextStyle,
    required super.receivedMessageCaptionTextStyle,
    required super.receivedMessageDocumentIconColor,
    required super.receivedMessageLinkDescriptionTextStyle,
    required super.receivedMessageLinkTitleTextStyle,
    required super.secondaryColor,
    required super.seenIcon,
    required super.sendButtonIcon,
    required super.sendButtonMargin,
    required super.sendingIcon,
    required super.sentEmojiMessageTextStyle,
    required super.sentMessageBodyTextStyle,
    required super.sentMessageCaptionTextStyle,
    required super.sentMessageDocumentIconColor,
    required super.sentMessageLinkDescriptionTextStyle,
    required super.sentMessageLinkTitleTextStyle,
    required super.statusIconPadding,
    required super.systemMessageTheme,
    required super.typingIndicatorTheme,
    required super.unreadHeaderTheme,
    required super.userAvatarImageBackgroundColor,
    required super.userAvatarNameColors,
    required super.userAvatarTextStyle,
    required super.userNameTextStyle,
  });
}
